name = "newsnow"
type = "javascript"
#pages_build_output_dir = "dist/output/public"
#compatibility_date = "2025-01-07"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"
database_id = "07ba3998-602b-4110-8607-e62f1148826a"
